import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
	const data = await fetch(
		"https://content.guardianapis.com/search?api-key=4c444140-8216-4eb9-a8a0-5392b4af62ae"
	);
	const news = await data.json();
	//console.log(todos.response.results);
	const newsTitle = news.response.results;

	return { props: { newsTitle } };
}

export default function Home({ newsTitle }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Tarefas para fazer:</h1>
			<ul className={styles.todolist}>
				{newsTitle.map((news) => (
					<li key={news.id}>{news.webTitle}</li>
				))}
			</ul>
		</div>
	);
}
