import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/NavBar";

export async function getStaticProps() {
	const data = await fetch(
		"https://content.guardianapis.com/search?api-key=4c444140-8216-4eb9-a8a0-5392b4af62ae&show-blocks=all"
	);
	const news = await data.json();
	const newsData = news.response.results;

	console.log(newsData.blocks?.main.publishedDate);
	return { props: { newsData } };
}

export default function Home({ newsData }) {
	return (
		<div className="">
			<Head>
				<title>The News Website</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar />
			<div className="mx-auto max-w-7xl">
				{newsData.map((news) => (
					<div key={news.id} className="bg-gray-200 p-5 m-5">
						<a href={news.webUrl}>
							<h1 className="text-3xl font-medium">{news.webTitle}</h1>
							<img
								src={news.blocks.main.elements[0].assets[0]?.file}
								alt="news image"
							/>
						</a>
						<h1 className="text-3xl font-medium">
							{news.blocks.body[0].bodyTextSummary}
						</h1>
						<h1 className="text-3xl font-medium">{news.webPublicationDate}</h1>
						<h1 className="text-3xl font-medium">{news.sectionName}</h1>
					</div>
				))}
			</div>
		</div>
	);
}
