import Head from "next/head";
import Link from "next/link";

export async function getStaticProps() {
	const data = await fetch(
		"https://content.guardianapis.com/search?api-key=4c444140-8216-4eb9-a8a0-5392b4af62ae&show-blocks=all"
	);
	const news = await data.json();
	const newsData = news.response.results;

	console.log(newsData.blocks?.main.publishedDate);
	return { props: { newsData } };
}

export default function Home({ newsData }) {
	return (
		<div className="">
			<Head>
				<title>The News Website</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="mx-auto max-w-7xl">
				{newsData.map((news) => (
					<div key={news.id} className="m-5 flex">
						<Link href={`/news/${news.blocks.main.id}`}>
							<img
								src={news.blocks.main?.elements[0].assets[0]?.file}
								alt="news image"
								className="w-96 h-56 object-cover mr-5 cursor-pointer"
							/>
						</Link>
						<div className="block">
							<p className="font-medium">{news.sectionName}</p>
							<Link href={`/news/${news.blocks.main.id}`}>
								<h1 className="w-80 text-2xl text-red-700 font-bold cursor-pointer">
									{news.webTitle.substring(0, 75)}
								</h1>
							</Link>

							<p className="w-96">
								{news.blocks.body[0].bodyTextSummary.substring(0, 150)}...
							</p>
							<p className="text-sm text-gray-600">{news.webPublicationDate}</p>
						</div>
					</div>
				))}
			</div>
		</div>
	);
}
