import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Search({ result }) {
	const [query, setQuery] = useState("");
	const [news, setNews] = useState({});

	const search = (evt) => {
		if (evt.key === "Enter") {
			fetch(
				`https://content.guardianapis.com/search?q=${query}&api-key=4c444140-8216-4eb9-a8a0-5392b4af62ae&show-blocks=all`
			)
				.then((res) => res.json())
				.then((res) => res.response.results)
				.then((result) => {
					setNews(result);
					setQuery("");
					console.log(result);
				});

			const result = res.response.results;
		}
	};

	return (
		<div>
			<Head>
				<title>The News Website</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="search-box">
				<input
					type="text"
					className="search-bar"
					placeholder="Search..."
					onChange={(e) => setQuery(e.target.value)}
					value={query}
					onKeyPress={search}
				/>
				{result.map((news) => (
					<div key={news.id} className="m-5 flex">
						<a href={news.webUrl} target="_blank" rel="noreferrer">
							<img
								src={news.blocks.main?.elements[0].assets[0]?.file}
								alt="news image"
								className="w-96 h-56 object-cover mr-5 cursor-pointer"
							/>
						</a>
						<div className="block">
							<p className="font-medium">{news.sectionName}</p>
							<a href={news.webUrl} target="_blank" rel="noreferrer">
								<h1 className="w-80 text-2xl text-red-700 font-bold cursor-pointer">
									{news.webTitle.substring(0, 75)}
								</h1>
							</a>

							<p className="w-96">
								{news.blocks.body[0].bodyTextSummary.substring(0, 150)}...
							</p>
							<p className="text-sm text-gray-600">{news.webPublicationDate}</p>
						</div>
					</div>
				))}
			</div>
		</div>
	);
}
